package com.paragon.responses.spec;

import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * The streamed output emitted by an apply patch tool call.
 *
 * @param callId The unique ID of the apply patch tool call generated by the model.
 * @param status The status of the apply patch tool call output. One of {@code completed} or {@code
 *     failed}.
 * @param id The unique ID of the apply patch tool call output. Populated when this item is returned
 *     via API.
 * @param output Optional human-readable log text from the apply patch tool (e.g., patch results or
 *     errors).
 */
public record ApplyPatchToolCallOutput(
    @NonNull String callId,
    @NonNull ApplyPatchToolCallStatus status,
    @Nullable String id,
    @Nullable String output)
    implements Item, ResponseOutput, ToolCallOutput {}
