package com.paragon.responses.spec;

import org.jspecify.annotations.NonNull;

/** A tool call representing a request to create, delete, or update files using diff patches. */
public final class ApplyPatchToolCall extends ToolCall implements Item, ResponseOutput {

  @NonNull String callId;
  @NonNull ApplyPatchOperation operation;
  @NonNull String status;

  /**
   * @param id The unique ID of the apply patch tool call. Populated when this item is returned via
   *     API.
   * @param callId The unique ID of the apply patch tool call generated by the model.
   * @param operation The specific {@link ApplyPatchCreateFileOperation}, {@link
   *     ApplyPatchDeleteFileOperation}, or instruction for the apply_patch tool call.
   * @param status The status of the apply patch tool call. One of {@code in_progress} or {@code
   *     completed}.
   */
  public ApplyPatchToolCall(
      String id,
      @NonNull String callId,
      @NonNull ApplyPatchOperation operation,
      @NonNull String status) {
    super(id);
    this.callId = callId;
    this.operation = operation;
    this.status = status;
  }
}
