package com.paragon.responses.spec;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * Represents a message generated by the AI model in previous interactions.
 *
 * <p>Assistant messages contain responses that the model has previously generated, providing
 * conversation context and history for subsequent interactions. These messages are essential for
 * maintaining multi-turn conversations, as they allow the model to understand what it has already
 * communicated.
 *
 * <p>Unlike other message types, this class is {@code non-sealed}, allowing for potential extension
 * if specialized assistant message types are needed in the future. Assistant messages are typically
 * created with an explicit status indicating whether the response generation was completed, is in
 * progress, or was incomplete.
 *
 * @see Message
 * @see DeveloperMessage
 * @see UserMessage
 */
@com.fasterxml.jackson.databind.annotation.JsonDeserialize(
    using = com.paragon.responses.json.MessageDeserializer.class)
public non-sealed class AssistantMessage extends Message {
  /**
   * Constructs an AssistantMessage with the specified content and status.
   *
   * <p>Assistant messages are typically created by the API after response generation, with the
   * status reflecting the completion state of that generation process.
   *
   * @param content the model-generated response content; must not be null
   * @param status the processing status of the response generation; indicates whether generation
   *     completed successfully, is ongoing, or failed
   */
  @JsonCreator
  public AssistantMessage(
      @JsonProperty("content") @NonNull List<MessageContent> content,
      @JsonProperty("status") @Nullable InputMessageStatus status) {
    super(content, status);
  }

  public static AssistantMessage of(
      @NonNull List<MessageContent> content, @Nullable InputMessageStatus status) {
    return new AssistantMessage(content, status);
  }

  /**
   * Returns the role identifier for this message type.
   *
   * <p>Assistant messages represent model-generated content from previous conversation turns and
   * are used to maintain conversation context.
   *
   * @return the string {@code "assistant"}
   */
  @Override
  public MessageRole role() {
    return MessageRole.ASSISTANT;
  }
}
