package com.paragon.responses.spec;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * The outputs generated by the code interpreter, such as logs or images. Can be null if no outputs
 * are available.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
  @JsonSubTypes.Type(value = CodeInterpreterOutputLogs.class, name = "logs"),
  @JsonSubTypes.Type(value = CodeInterpreterOutputImage.class, name = "image")
})
public sealed interface CodeInterpreterOutput
    permits CodeInterpreterOutputLogs, CodeInterpreterOutputImage {}
