package com.paragon.responses.spec;

import java.util.List;
import org.jspecify.annotations.NonNull;

/** A tool call to run code. */
public final class CodeInterpreterToolCall extends ToolCall implements Item, ResponseOutput {

  @NonNull String code;
  @NonNull String containerId;
  @NonNull List<CodeInterpreterOutput> outputs;
  @NonNull CodeInterpreterToolCallStatus status;

  /**
   * @param code The code to run, or null if not available.
   * @param containerId The ID of the container used to run the code.
   * @param id The unique ID of the code interpreter tool call.
   * @param outputs The outputs generated by the code interpreter, such as logs or images. Can be
   *     null if no outputs are available.
   * @param status The status of the code interpreter tool call. Valid values are {@code
   *     in_progress}, {@code completed}, {@code incomplete}, interpreting, and failed.
   */
  CodeInterpreterToolCall(
      @NonNull String id,
      @NonNull String code,
      @NonNull String containerId,
      @NonNull List<CodeInterpreterOutput> outputs,
      @NonNull CodeInterpreterToolCallStatus status) {
    super(id);
    this.code = code;
    this.containerId = containerId;
    this.outputs = outputs;
    this.status = status;
  }
}
