package com.paragon.responses.spec;

import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * The output of a custom tool call from your code, being sent back to the model.
 *
 * @param callId The call ID, used to map this custom tool call output to a custom tool call.
 * @param output The output from the custom tool call generated by your code. Can be a string or an
 *     list of output content.
 * @param id The unique ID of the custom tool call output in the OpenAI platform.
 */
public record CustomToolCallOutput(
    @NonNull String callId, @NonNull CustomToolCallOutputKind output, @Nullable String id)
    implements Item, ToolCallOutput {}
