package com.paragon.responses.spec;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * The output from the custom tool call generated by your code. Can be a string or an list of output
 * content. This is a sealed interface. Allowed implementations are:
 *
 * <ul>
 *   <li>{@link Text} - A text input to the model.
 *   <li>{@link Image} - An image input to the model. Learn about <a
 *       href="https://platform.openai.com/docs/guides/images-vision?api-mode=responses">image
 *       inputs.</a>
 *   <li>{@link File} - A file input to the model.
 * </ul>
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
  @JsonSubTypes.Type(value = Text.class, name = "input_text"),
  @JsonSubTypes.Type(value = Image.class, name = "input_image"),
  @JsonSubTypes.Type(value = File.class, name = "input_file")
})
public sealed interface CustomToolCallOutputKind permits Text, Image, File {}
