package com.paragon.responses.spec;

import java.util.Objects;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/** A call to a custom tool created by the model. */
public final class CustomToolCall extends ToolCall implements Item, ResponseOutput {
  private final @NonNull String callId;
  private final @NonNull String input;
  private final @NonNull String name;

  /**
   * @param callId An identifier used to map this custom tool call to a tool call output.
   * @param input The input for the custom tool call generated by the model.
   * @param name The name of the custom tool being called.
   * @param id The unique ID of the custom tool call in the OpenAI platform.
   */
  public CustomToolCall(
      @NonNull String callId, @NonNull String input, @NonNull String name, @Nullable String id) {
    super(id);
    this.callId = callId;
    this.input = input;
    this.name = name;
  }

  public @NonNull String callId() {
    return callId;
  }

  public @NonNull String input() {
    return input;
  }

  public @NonNull String name() {
    return name;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) return true;
    if (obj == null || obj.getClass() != this.getClass()) return false;
    var that = (CustomToolCall) obj;
    return Objects.equals(this.callId, that.callId)
        && Objects.equals(this.input, that.input)
        && Objects.equals(this.name, that.name)
        && Objects.equals(this.id, that.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callId, input, name, id);
  }

  @Override
  public String toString() {
    return "CustomToolCall["
        + "callId="
        + callId
        + ", "
        + "input="
        + input
        + ", "
        + "name="
        + name
        + ", "
        + "id="
        + id
        + ']';
  }
}
