package com.paragon.responses.spec;

import java.util.List;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * The streamed output items emitted by a function shell tool call.
 *
 * @param callId The unique ID of the function shell tool call generated by the model.
 * @param output Captured chunks of stdout and stderr output, along with their associated outcomes.
 * @param id The unique ID of the function shell tool call output. Populated when this item is
 *     returned via API.
 * @param maxOutputLength The maximum number of UTF-8 characters captured for this shell call's
 *     combined output.
 */
public record FunctionShellToolCallOutput(
    @NonNull String callId,
    @NonNull List<FunctionShellToolCallOutputChunk> output,
    @Nullable String id,
    @Nullable Integer maxOutputLength)
    implements Item, ToolCallOutput {}
