package com.paragon.responses.spec;

import java.util.Objects;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/** A tool representing a request to execute one or more shell commands. */
public final class FunctionShellToolCall extends ToolCall implements Item, ResponseOutput {
  private final @NonNull FunctionShellAction action;
  private final @NonNull String callId;
  private final @Nullable FunctionShellToolCallStatus status;

  /**
   * @param action The shell commands and limits that describe how to run the tool call.
   * @param callId The unique ID of the function shell tool call generated by the model.
   * @param id The unique ID of the function shell tool call. Populated when this item is returned
   *     via API.
   * @param status The status of the shell call. One of {@code in_progress}, {@code completed}, or
   *     {@code incomplete}.
   */
  public FunctionShellToolCall(
      @NonNull FunctionShellAction action,
      @NonNull String callId,
      @Nullable String id,
      @Nullable FunctionShellToolCallStatus status) {
    super(id);
    this.action = action;
    this.callId = callId;
    this.status = status;
  }

  public @NonNull FunctionShellAction action() {
    return action;
  }

  public @NonNull String callId() {
    return callId;
  }

  @Override
  public @Nullable String id() {
    return id;
  }

  public @Nullable FunctionShellToolCallStatus status() {
    return status;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) return true;
    if (obj == null || obj.getClass() != this.getClass()) return false;
    var that = (FunctionShellToolCall) obj;
    return Objects.equals(this.action, that.action)
        && Objects.equals(this.callId, that.callId)
        && Objects.equals(this.id, that.id)
        && Objects.equals(this.status, that.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, callId, id, status);
  }

  @Override
  public String toString() {
    return "FunctionShellToolCall["
        + "action="
        + action
        + ", "
        + "callId="
        + callId
        + ", "
        + "id="
        + id
        + ", "
        + "status="
        + status
        + ']';
  }
}
