package com.paragon.responses.spec;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/** A tool call to run a function. See the function calling guide for more information. */
@com.fasterxml.jackson.annotation.JsonTypeName("function_call")
public non-sealed class FunctionToolCall extends ToolCall implements Item, ResponseOutput {
  private final @NonNull String arguments;
  private final @NonNull String callId;
  private final @NonNull String name;
  private final @Nullable FunctionToolCallStatus status;

  /**
   * @param arguments A JSON string of the arguments to pass to the function.
   * @param callId The unique ID of the function tool call generated by the model.
   * @param name The name of the function to run.
   * @param id The unique ID of the function tool call.
   * @param status The status of the item. One of {@code in_progress}, {@code completed}, or {@code
   *     incomplete}. Populated when items are returned via API.
   */
  @JsonCreator
  public FunctionToolCall(
      @JsonProperty("arguments") @NonNull String arguments,
      @JsonProperty("call_id") @NonNull String callId,
      @JsonProperty("name") @NonNull String name,
      @JsonProperty("id") @Nullable String id,
      @JsonProperty("status") @Nullable FunctionToolCallStatus status) {
    super(id);
    this.arguments = arguments;
    this.callId = callId;
    this.name = name;
    this.status = status;
  }

  @Override
  public @NonNull String toString() {
    return String.format(
        """
        <function_tool_call>
            <call_id>%s</call_id>
            <name>%s</name>
            <arguments>%s</arguments>
            <id>%s</id>
            <status>%s</status>
        </function_tool_call>
        """,
        callId, name, arguments, id != null ? id : "null", status != null ? status : "null");
  }

  @JsonProperty("arguments")
  public @NonNull String arguments() {
    return arguments;
  }

  @JsonProperty("call_id")
  public @NonNull String callId() {
    return callId;
  }

  @JsonProperty("name")
  public @NonNull String name() {
    return name;
  }

  @JsonProperty("id")
  @Override
  public @Nullable String id() {
    return id;
  }

  @JsonProperty("status")
  public @Nullable FunctionToolCallStatus status() {
    return status;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) return true;
    if (obj == null || obj.getClass() != this.getClass()) return false;
    var that = (FunctionToolCall) obj;
    return Objects.equals(this.arguments, that.arguments)
        && Objects.equals(this.callId, that.callId)
        && Objects.equals(this.name, that.name)
        && Objects.equals(this.id, that.id)
        && Objects.equals(this.status, that.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arguments, callId, name, id, status);
  }
}
