package com.paragon.responses.spec;

import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * The output of a function tool call.
 *
 * @param callId The unique ID of the function tool call generated by the model.
 * @param output {@link Text}, {@link Image}, or {@link File} output of the function tool call.
 * @param id The unique ID of the function tool call output. Populated when this item is returned
 *     via API.
 * @param status The {@link FunctionToolCallOutputStatus} of the item. One of {@code in_progress},
 *     {@code completed}, or {@code incomplete}. Populated when items are returned via API.
 */
public record FunctionToolCallOutput(
    @NonNull String callId,
    @NonNull FunctionToolCallOutputKind output,
    @Nullable String id,
    @Nullable FunctionToolCallOutputStatus status)
    implements Item, ToolCallOutput {
  /**
   * Creates a successful text output with a generated call ID.
   *
   * @param message The success message
   * @return A FunctionToolCallOutput with the text
   */
  public static FunctionToolCallOutput success(@NonNull String message) {
    return new FunctionToolCallOutput(
        generateCallId(), new Text(message), null, FunctionToolCallOutputStatus.COMPLETED);
  }

  /**
   * Creates a successful text output with a specific call ID.
   *
   * @param callId The call ID
   * @param message The success message
   * @return A FunctionToolCallOutput with the text
   */
  public static FunctionToolCallOutput success(@NonNull String callId, @NonNull String message) {
    return new FunctionToolCallOutput(
        callId, new Text(message), null, FunctionToolCallOutputStatus.COMPLETED);
  }

  /**
   * Creates an error text output with a generated call ID.
   *
   * @param errorMessage The error message
   * @return A FunctionToolCallOutput with the error text
   */
  public static FunctionToolCallOutput error(@NonNull String errorMessage) {
    return new FunctionToolCallOutput(
        generateCallId(),
        new Text("Error: " + errorMessage),
        null,
        FunctionToolCallOutputStatus.INCOMPLETE);
  }

  /**
   * Creates an error text output with a specific call ID.
   *
   * @param callId The call ID
   * @param errorMessage The error message
   * @return A FunctionToolCallOutput with the error text
   */
  public static FunctionToolCallOutput error(@NonNull String callId, @NonNull String errorMessage) {
    return new FunctionToolCallOutput(
        callId, new Text("Error: " + errorMessage), null, FunctionToolCallOutputStatus.INCOMPLETE);
  }

  /**
   * Creates an in-progress text output with a generated call ID.
   *
   * @param message The progress message
   * @return A FunctionToolCallOutput with in-progress status
   */
  public static FunctionToolCallOutput inProgress(@NonNull String message) {
    return new FunctionToolCallOutput(
        generateCallId(), new Text(message), null, FunctionToolCallOutputStatus.IN_PROGRESS);
  }

  /**
   * Creates an in-progress text output with a specific call ID.
   *
   * @param callId The call ID
   * @param message The progress message
   * @return A FunctionToolCallOutput with in-progress status
   */
  public static FunctionToolCallOutput inProgress(@NonNull String callId, @NonNull String message) {
    return new FunctionToolCallOutput(
        callId, new Text(message), null, FunctionToolCallOutputStatus.IN_PROGRESS);
  }

  /**
   * Creates an output with an image result.
   *
   * @param image The image output
   * @return A FunctionToolCallOutput with the image
   */
  public static FunctionToolCallOutput withImage(@NonNull Image image) {
    return new FunctionToolCallOutput(
        generateCallId(), image, null, FunctionToolCallOutputStatus.COMPLETED);
  }

  /**
   * Creates an output with an image result and specific call ID.
   *
   * @param callId The call ID
   * @param image The image output
   * @return A FunctionToolCallOutput with the image
   */
  public static FunctionToolCallOutput withImage(@NonNull String callId, @NonNull Image image) {
    return new FunctionToolCallOutput(callId, image, null, FunctionToolCallOutputStatus.COMPLETED);
  }

  /**
   * Creates an output with a file result.
   *
   * @param file The file output
   * @return A FunctionToolCallOutput with the file
   */
  public static FunctionToolCallOutput withFile(@NonNull File file) {
    return new FunctionToolCallOutput(
        generateCallId(), file, null, FunctionToolCallOutputStatus.COMPLETED);
  }

  /**
   * Creates an output with a file result and specific call ID.
   *
   * @param callId The call ID
   * @param file The file output
   * @return A FunctionToolCallOutput with the file
   */
  public static FunctionToolCallOutput withFile(@NonNull String callId, @NonNull File file) {
    return new FunctionToolCallOutput(callId, file, null, FunctionToolCallOutputStatus.COMPLETED);
  }

  /**
   * Generates a unique call ID.
   *
   * @return A unique call ID string
   */
  private static String generateCallId() {
    return "call_" + java.util.UUID.randomUUID().toString().replace("-", "");
  }

  @Override
  public @NonNull String toString() {
    return output.toString();
  }
}
