package com.paragon.responses.spec;

import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/**
 * The output of a local shell tool call.
 *
 * @param id The unique ID of the local shell tool call generated by the model.
 * @param output A JSON string of the output of the local shell tool call.
 * @param status The status of the item. One of {@code in_progress}, {@code completed}, or {@code
 *     incomplete}.
 */
public record LocalShellCallOutput(
    @NonNull String id, @NonNull String output, @Nullable LocalShellCallOutputStatus status)
    implements Item, ToolCallOutput {}
