package com.paragon.responses.spec;

import java.util.Objects;
import org.jspecify.annotations.NonNull;

/** A tool call to run a command on the local shell. */
public final class LocalShellCall extends ToolCall implements Item, ResponseOutput {
  private final @NonNull LocalShellAction action;
  private final @NonNull String callId;
  private final @NonNull String status;

  /**
   * @param action Execute a shell command on the server. See {@link LocalShellAction}
   * @param callId The unique ID of the local shell tool call generated by the model.
   * @param id The unique ID of the local shell call.
   * @param status The status of the local shell call.
   */
  public LocalShellCall(
      @NonNull LocalShellAction action,
      @NonNull String callId,
      @NonNull String id,
      @NonNull String status) {
    super(id);
    this.action = action;
    this.callId = callId;
    this.status = status;
  }

  public @NonNull LocalShellAction action() {
    return action;
  }

  public @NonNull String callId() {
    return callId;
  }

  @Override
  public @NonNull String id() {
    return id;
  }

  public @NonNull String status() {
    return status;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) return true;
    if (obj == null || obj.getClass() != this.getClass()) return false;
    var that = (LocalShellCall) obj;
    return Objects.equals(this.action, that.action)
        && Objects.equals(this.callId, that.callId)
        && Objects.equals(this.id, that.id)
        && Objects.equals(this.status, that.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, callId, id, status);
  }

  @Override
  public String toString() {
    return "LocalShellCall["
        + "action="
        + action
        + ", "
        + "callId="
        + callId
        + ", "
        + "id="
        + id
        + ", "
        + "status="
        + status
        + ']';
  }
}
