package com.paragon.responses.spec;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * An array of content items generated by the model.
 *
 * <p>The length and order of items in the output array is dependent on the model's response. Rather
 * than accessing the first item in the output array and assuming it's an assistant message with the
 * content generated by the model, you might consider using the output_text property where supported
 * in SDKs.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
  @JsonSubTypes.Type(value = OutputMessage.class, name = "message"),
  @JsonSubTypes.Type(value = FileSearchToolCall.class, name = "file_search_tool_call"),
  @JsonSubTypes.Type(value = FunctionToolCall.class, name = "function_call"),
  @JsonSubTypes.Type(value = WebSearchToolCall.class, name = "web_search_call"),
  @JsonSubTypes.Type(value = ComputerToolCall.class, name = "computer_call"),
  @JsonSubTypes.Type(value = Reasoning.class, name = "reasoning"),
  @JsonSubTypes.Type(value = ImageGenerationCall.class, name = "image_generation_call"),
  @JsonSubTypes.Type(value = CodeInterpreterToolCall.class, name = "code_interpreter_call"),
  @JsonSubTypes.Type(value = LocalShellCall.class, name = "local_shell_call"),
  @JsonSubTypes.Type(value = FunctionShellToolCall.class, name = "function_shell_call"),
  @JsonSubTypes.Type(value = ShellCallOutput.class, name = "shell_call_output"),
  @JsonSubTypes.Type(value = ApplyPatchToolCall.class, name = "apply_patch_call"),
  @JsonSubTypes.Type(value = ApplyPatchToolCallOutput.class, name = "apply_patch_call_output"),
  @JsonSubTypes.Type(value = McpToolCall.class, name = "mcp_call"),
  @JsonSubTypes.Type(value = McpListTools.class, name = "mcp_list_tools"),
  @JsonSubTypes.Type(value = McpApprovalRequest.class, name = "mcp_approval_request"),
  @JsonSubTypes.Type(value = CustomToolCall.class, name = "custom_tool_call")
})
public sealed interface ResponseOutput
    permits OutputMessage,
        FileSearchToolCall,
        FunctionToolCall,
        WebSearchToolCall,
        ComputerToolCall,
        Reasoning,
        ImageGenerationCall,
        CodeInterpreterToolCall,
        LocalShellCall,
        FunctionShellToolCall,
        ShellCallOutput,
        ApplyPatchToolCall,
        ApplyPatchToolCallOutput,
        McpToolCall,
        McpListTools,
        McpApprovalRequest,
        CustomToolCall {}
